# Generated by Django 4.2.3 on 2023-07-16 23:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('twitch_link', models.URLField(max_length=50)),
            ],
            options={
                'verbose_name': 'Streamer',
                'verbose_name_plural': 'Streamers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar_image', models.URLField()),
                ('biography', models.TextField()),
            ],
            options={
                'verbose_name': 'Viewer',
                'verbose_name_plural': 'Viewers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('streamer', models.ManyToManyField(related_name='trait', to='users.streamer')),
                ('viewer', models.ManyToManyField(related_name='trait', to='users.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('streamer', models.ManyToManyField(related_name='language', to='users.streamer')),
                ('viewer', models.ManyToManyField(related_name='language', to='users.viewer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('descriptions', models.CharField(max_length=100)),
                ('streamer', models.ManyToManyField(related_name='category', to='users.streamer')),
                ('viewer', models.ManyToManyField(related_name='category', to='users.viewer')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
